# Generated by Django 5.1.15 on 2026-03-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome template')),
                ('subject', models.CharField(max_length=200, verbose_name='Oggetto email')),
                ('body', models.TextField(verbose_name='Corpo email')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template predefinito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Template email',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Data di nascita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome sede')),
                ('timezone', models.CharField(default='Europe/Rome', max_length=50, verbose_name='Fuso orario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
            },
        ),
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(verbose_name='Data invio')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Avviato il')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Destinatari totali')),
                ('total_celebrants', models.IntegerField(default=0, verbose_name='Festeggiati totali')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('RUNNING', 'In esecuzione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Messaggio di errore')),
                ('template_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.emailtemplate', verbose_name='Template utilizzato')),
            ],
            options={
                'verbose_name': 'Log invio',
                'verbose_name_plural': 'Log invii',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SendLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Inviata il')),
                ('success', models.BooleanField(default=True, verbose_name='Successo')),
                ('error_detail', models.TextField(blank=True, null=True, verbose_name='Dettaglio errore')),
                ('celebrants_included', models.ManyToManyField(blank=True, related_name='celebrated_in_logs', to='newsletter.employee', verbose_name='Festeggiati inclusi')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='newsletter.sendlog', verbose_name='Log invio')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_logs', to='newsletter.employee', verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Riga log invio',
                'verbose_name_plural': 'Righe log invio',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome team')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='newsletter.office', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'unique_together': {('office', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='newsletter.team', verbose_name='Team'),
        ),
    ]
